package utils

type EnvironmentVariable string

const (
	DATASTORE_DATASET            = "DATASTORE_DATASET"
	DATASTORE_EMULATOR_HOST      = "DATASTORE_EMULATOR_HOST"
	DATASTORE_EMULATOR_HOST_PATH = "DATASTORE_EMULATOR_HOST_PATH"
	DATASTORE_HOST               = "DATASTORE_HOST"
	DATASTORE_PROJECT_ID         = "DATASTORE_PROJECT_ID"
)
